### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by pmajkutewicz** [pbadenski/halik#3]
`java.lang.NullPointerException
    at org.springframework.util.ConcurrentReferenceHashMap$Segment.access$400(ConcurrentReferenceHashMap.java:411)
    at org.springframework.util.ConcurrentReferenceHashMap$EntryIterator.moveToNextSegment(ConcurrentReferenceHashMap.java:890)
    at org.springframework.util.ConcurrentReferenceHashMap$EntryIterator.<init>(ConcurrentReferenceHashMap.java:842)
    at org.springframework.util.ConcurrentReferenceHashMap$EntrySet.iterator(ConcurrentReferenceHashMap.java:787)
    at java.util.AbstractMap.toString(AbstractMap.java:524)
    at java.lang.String.valueOf(String.java:2994)
    at java.lang.StringBuilder.append(StringBuilder.java:131)
    at io.halik.agent.capture.track.variables.c.toString(MyApplication:42)
    at io.halik.agent.capture.a.c.a(MyApplication:73)
    at io.halik.agent.capture.c.apply(MyApplication:1065)
    at io.halik.agent.capture.track.variables.g.a(MyApplication:63)
    at io.halik.agent.capture.b.a(MyApplication:62)
    at io.halik.agent.capture.h.a(MyApplication:163)
    at io.halik.agent.capture.FlowFacade.captureLineExecution(MyApplication:29)
    at org.springframework.util.ConcurrentReferenceHashMap.createReferenceManager(ConcurrentReferenceHashMap.java:203)
    at org.springframework.util.ConcurrentReferenceHashMap$Segment.<init>(ConcurrentReferenceHashMap.java:437)
    at org.springframework.util.ConcurrentReferenceHashMap.<init>(ConcurrentReferenceHashMap.java:180)
    at org.springframework.util.ConcurrentReferenceHashMap.<init>(ConcurrentReferenceHashMap.java:112)
    at org.springframework.util.ReflectionUtils.<clinit>(ReflectionUtils.java:63)
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:105)
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:130)
    at org.springframework.test.context.ContextLoaderUtils.resolveContextLoader(ContextLoaderUtils.java:118)
    at org.springframework.test.context.ContextLoaderUtils.buildMergedContextConfiguration(ContextLoaderUtils.java:594)
    at org.springframework.test.context.ContextLoaderUtils.buildMergedContextConfiguration(ContextLoaderUtils.java:560)
    at org.springframework.test.context.TestContext.<init>(TestContext.java:98)
    at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:121)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTestContextManager(SpringJUnit4ClassRunner.java:119)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.<init>(SpringJUnit4ClassRunner.java:108)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
    at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
    at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
    at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:96)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)`

**Comment by pbadenski** [comment]
Fixed in [0.0.5.3](https://plugins.jetbrains.com/update/index?pr=&updateId=26453)
